(self.AMP=self.AMP||[]).push({n:"amp-form",v:"1810021759000",f:(function(AMP,_){
var m;function n(a,b){function c(){}c.prototype=b.prototype;a.prototype=new c;a.prototype.constructor=a;for(var d in b)if(Object.defineProperties){var e=Object.getOwnPropertyDescriptor(b,d);e&&Object.defineProperty(a,d,e)}else a[d]=b[d]}function aa(a,b){b=void 0===b?"":b;try{return decodeURIComponent(a)}catch(c){return b}};var ba=/(?:^[#?]?|&)([^=&]+)(?:=([^&]*))?/g;var ca=Object.prototype.toString;function da(a){if(!a)return[];for(var b=Array(a.length),c=0;c<a.length;c++)b[c]=a[c];return b}function ea(a){return"[object Object]"===ca.call(a)};self.log=self.log||{user:null,dev:null,userForEmbed:null};var p=self.log;function q(){if(!p.user)throw Error("failed to call initLogConstructor");return p.user}function fa(){if(p.dev)return p.dev;throw Error("failed to call initLogConstructor");};var ga=Object.prototype.hasOwnProperty;function r(){var a,b=Object.create(null);a&&Object.assign(b,a);return b}function u(a){return a||{}}
function ha(a,b){var c;c=void 0===c?10:c;var d=[],e=[];e.push({t:a,s:b,d:0});for(a={};0<e.length;){b=e.shift();a.t=b.t;a.s=b.s;a.d=b.d;if(d.includes(a.s))throw Error("Source object has a circular reference.");d.push(a.s);a.t!==a.s&&(a.d>c?Object.assign(a.t,a.s):(Object.keys(a.s).forEach(function(a){return function(b){var c=a.s[b];if(ga.call(a.t,b)){var d=a.t[b];if(ea(c)&&ea(d)){e.push({t:d,s:c,d:a.d+1});return}}a.t[b]=c}}(a)),a={s:a.s,t:a.t,d:a.d}))}};function ia(){var a,b;this.promise=new Promise(function(c,d){a=c;b=d});this.resolve=a;this.reject=b}function ja(a){return new Promise(function(b){b(a())})}function ka(a){var b,c;this.X=new Promise(function(a,d){b=a;c=d});this.ga=b;this.ea=c;this.P=0;if(a)for(var d=0;d<a.length;d++)this.add(a[d])}ka.prototype.add=function(a){var b=this,c=++this.P;Promise.resolve(a).then(function(a){b.P===c&&b.ga(a)},function(a){b.P===c&&b.ea(a)});return this.X};
ka.prototype.then=function(a,b){return this.X.then(a,b)};function v(a,b){if(a.nodeType){var c=(a.ownerDocument||a).defaultView;if(c=c!=(c.__AMP_TOP||c)&&la(c,b)?w(c,b):null)return c}return x(a,b)}function y(a,b){a=a.__AMP_TOP||a;return w(a,b)}function x(a,b){a=z(a);a=A(a);return w(a,b)}function z(a){return a.nodeType?y((a.ownerDocument||a).defaultView,"ampdoc").getAmpDoc(a):a}function A(a){a=z(a);return a.isSingleDoc()?a.win:a}
function w(a,b){la(a,b);var c=ma(a);a=c[b];a.obj||(a.obj=new a.ctor(a.context),a.ctor=null,a.context=null,a.resolve&&a.resolve(a.obj));return a.obj}function na(a){var b=ma(a)["amp-analytics-instrumentation"];if(b){if(b.promise)return b.promise;w(a,"amp-analytics-instrumentation");return b.promise=Promise.resolve(b.obj)}return null}function ma(a){var b=a.services;b||(b=a.services={});return b}function la(a,b){a=a.services&&a.services[b];return!(!a||!a.ctor&&!a.obj)};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
var oa=/(\0)|^(-)$|([\x01-\x1f\x7f]|^-?[0-9])|([\x80-\uffff0-9a-zA-Z_-]+)|[^]/g;function pa(a,b,c,d,e){return e?e:b?"\ufffd":d?a.slice(0,-1)+"\\"+a.slice(-1).charCodeAt(0).toString(16)+" ":"\\"+a};function qa(a,b){return b.length>a.length?!1:0==a.lastIndexOf(b,0)};var B;function ra(a,b){for(var c=[],d=a.parentElement;d;d=d.parentElement)b(d)&&c.push(d);return c}function sa(a){var b="fieldset",b=b.toUpperCase();return ra(a,function(a){return a.tagName==b})}function C(a,b){for(var c=0,d;void 0!==(d=a[c]);c++)b(d,c)};function ta(a){var b=z(a),c=na(A(a));return c?c:b.whenBodyAvailable().then(function(){var a;a=b.win;var c=b.getHeadNode(),g;if(c){g=[];for(var c=c.querySelectorAll("script[custom-element]"),f=0;f<c.length;f++)g.push(c[f].getAttribute("custom-element"))}else g=[];a=g.includes("amp-analytics")?y(a,"extensions").waitForExtension(a,"amp-analytics"):Promise.resolve();return a}).then(function(){var c;c=b.win;if(c.ampExtendedElements&&c.ampExtendedElements["amp-analytics"]){c=A(a);var e=na(c);if(!e){var g=
new ia,e=g.promise,g=g.resolve;ma(c)["amp-analytics-instrumentation"]={obj:null,promise:e,resolve:g,context:null,ctor:null}}c=e}else c=null;return c})};function D(a){this.ca=a;this.O=this.V=0;this.I=Object.create(null)}D.prototype.has=function(a){return!!this.I[a]};D.prototype.get=function(a){var b=this.I[a];if(b)return b.access=++this.O,b.payload};D.prototype.put=function(a,b){this.has(a)||this.V++;this.I[a]={payload:b,access:this.O};if(!(this.V<=this.ca)){fa().warn("lru-cache","Trimming LRU cache");a=this.I;var c=this.O+1,d,e;for(e in a){var g=a[e].access;g<c&&(c=g,d=e)}void 0!==d&&(delete a[d],this.V--)}};var E=self.AMP_CONFIG||{},ua={thirdParty:E.thirdPartyUrl||"https://3p.ampproject.net",thirdPartyFrameHost:E.thirdPartyFrameHost||"ampproject.net",thirdPartyFrameRegex:("string"==typeof E.thirdPartyFrameRegex?new RegExp(E.thirdPartyFrameRegex):E.thirdPartyFrameRegex)||/^d-\d+\.ampproject\.net$/,cdn:E.cdnUrl||"https://cdn.ampproject.org",cdnProxyRegex:("string"==typeof E.cdnProxyRegex?new RegExp(E.cdnProxyRegex):E.cdnProxyRegex)||/^https:\/\/([a-zA-Z0-9_-]+\.)?cdn\.ampproject\.org$/,localhostRegex:/^https?:\/\/localhost(:\d+)?$/,
errorReporting:E.errorReportingUrl||"https://amp-error-reporting.appspot.com/r",localDev:E.localDev||!1};var va=u({c:!0,v:!0,a:!0,ad:!0}),wa,xa,ya=/[?&]amp_js[^&]*/,za=/[?&]amp_gsa[^&]*/,Aa=/[?&]amp_r[^&]*/,Ba=/[?&]usqp[^&]*/;
function F(a){var b;wa||(wa=self.document.createElement("a"),xa=self.UrlCache||(self.UrlCache=new D(100)));var c=b?null:xa,d=wa;if(c&&c.has(a))a=c.get(a);else{d.href=a;d.protocol||(d.href=d.href);var e={href:d.href,protocol:d.protocol,host:d.host,hostname:d.hostname,port:"0"==d.port?"":d.port,pathname:d.pathname,search:d.search,hash:d.hash,origin:null};"/"!==e.pathname[0]&&(e.pathname="/"+e.pathname);if("http:"==e.protocol&&80==e.port||"https:"==e.protocol&&443==e.port)e.port="",e.host=e.hostname;
e.origin=d.origin&&"null"!=d.origin?d.origin:"data:"!=e.protocol&&e.host?e.protocol+"//"+e.host:e.href;c&&c.put(a,e);a=e}return a}function Da(a,b,c){if(!b)return a;var d=a.split("#",2),e=d[0].split("?",2),g=e[0]+(e[1]?c?"?"+b+"&"+e[1]:"?"+e[1]+"&"+b:"?"+b);return g+=d[1]?"#"+d[1]:""}
function Ea(a){"string"==typeof a&&(a=F(a));var b=a;"string"==typeof b&&(b=F(b));if(!ua.cdnProxyRegex.test(b.origin))return a.href;var b=a.pathname.split("/"),c=b[1];q().assert(va[c],"Unknown path prefix in url %s",a.href);var d=b[2],e="s"==d?"https://"+decodeURIComponent(b[3]):"http://"+decodeURIComponent(d);q().assert(0<e.indexOf("."),"Expected a . in origin %s",e);b.splice(1,"s"==d?3:2);b=e+b.join("/");c=(c=a.search)&&"?"!=c?(c=c.replace(ya,"").replace(za,"").replace(Aa,"").replace(Ba,"").replace(/^[?&]/,
""))?"?"+c:"":"";return b+c+(a.hash||"")};function Fa(a,b,c,d){var e={detail:c};Object.assign(e,d);if("function"==typeof a.CustomEvent)return new a.CustomEvent(b,e);a=a.document.createEvent("CustomEvent");a.initCustomEvent(b,!!e.bubbles,!!e.cancelable,c);return a};var G,Ga="Webkit webkit Moz moz ms O o".split(" ");function Ha(a,b){void 0===b&&(b=a.hasAttribute("hidden"));b?a.removeAttribute("hidden"):a.setAttribute("hidden","")};function Ia(a,b){var c='form.amp-form-submit-error [submit-error],form.amp-form-submit-success [submit-success],form.amp-form-submitting [submitting]{display:block}.i-amphtml-validation-bubble{-webkit-transform:translate(-50%,-100%);transform:translate(-50%,-100%);background-color:#fff;box-shadow:0 5px 15px 0 rgba(0,0,0,0.5);max-width:200px;position:absolute;display:block;box-sizing:border-box;padding:10px;border-radius:5px}.i-amphtml-validation-bubble:after{content:" ";position:absolute;bottom:-8px;left:30px;width:0;height:0;border-left:8px solid transparent;border-right:8px solid transparent;border-top:8px solid #fff}[visible-when-invalid]{display:none;color:red}[visible-when-invalid].visible{display:initial}\n/*# sourceURL=/extensions/amp-form/0.1/amp-form.css*/',
d=!1,e="amp-form",g=a.getHeadNode(),f=Ja(g,Ka(g,c),d||!1,e||null);if(b){var h=a.getRootNode();if(La(h,f))b(f);else var k=setInterval(function(){La(h,f)&&(clearInterval(k),b(f))},4)}}
function Ja(a,b,c,d){var e=a.__AMP_CSS_SM;e||(e=a.__AMP_CSS_SM=r());var g=!c&&d&&"amp-custom"!=d&&"amp-keyframes"!=d,f=c?"amp-runtime":g?"amp-extension="+d:null;if(f){var h=Ma(a,e,f);if(h)return h.textContent!==b&&(h.textContent=b),h}var k=(a.ownerDocument||a).createElement("style");k.textContent=b;var l=null;c?k.setAttribute("amp-runtime",""):g?(k.setAttribute("amp-extension",d||""),l=Ma(a,e,"amp-runtime")):(d&&k.setAttribute(d,""),l=a.lastChild);b=l;a.insertBefore(k,b?b.nextSibling:a.firstChild);
f&&(e[f]=k);return k}function Ma(a,b,c){return b[c]?b[c]:(a=a.querySelector("style["+c+"]"))?b[c]=a:null}function Ka(a,b){return(a=a.__AMP_CSS_TR)?a(b):b}function La(a,b){var c=a.styleSheets;for(a=0;a<c.length;a++){var d=c[a];if(d.ownerNode==b)return!0}return!1};function Na(a,b,c){ta(a).then(function(d){d&&d.triggerEventForTarget(a,b,c)})};function H(a){var b={},c=a.elements,d=/^(?:input|select|textarea)$/i,e=/^(?:button|image|file|reset)$/i,g=/^(?:checkbox|radio)$/i;for(a=0;a<c.length;a++){var f=c[a],h;if(h=f.name){a:if(f.disabled)h=!0;else{h=sa(f);for(var k=0;k<h.length;k++)if(h[k].disabled){h=!0;break a}h=!1}h=!h}!h||!d.test(f.tagName)||e.test(f.type)||g.test(f.type)&&!f.checked||(void 0===b[f.name]&&(b[f.name]=[]),b[f.name].push(f.value))}return b};function I(a){this.A=new FormData(a);this.K=this.A.entries?null:a?H(a):r()}I.prototype.append=function(a,b){if(!this.A.entries){var c=String(a);this.K[c]=this.K[c]||[];this.K[a].push(String(b))}return this.A.append(a,b)};I.prototype.entries=function(){if(this.A.entries)return this.A.entries();var a=[],b=this.K;Object.keys(b).forEach(function(c){b[c].forEach(function(b){return a.push([c,b])})});var c=0;return{next:function(){return c<a.length?{value:a[c++],done:!1}:{value:void 0,done:!0}}}};
I.prototype.getFormData=function(){return this.A};var Oa=["GET","POST"];
function Pa(a,b){q().assert(ea(a),"Object expected: %s",a);var c="document"==b;if(!c)return new Response(a.body,a.init);var d=r(),e={status:200,statusText:"OK",getResponseHeader:function(a){return d[String(a).toLowerCase()]||null}};if(a.init){var g=a.init;Array.isArray(g.headers)&&g.headers.forEach(function(a){var b=a[0],c=a[1];d[String(b).toLowerCase()]=String(c)});g.status&&(e.status=parseInt(g.status,10));g.statusText&&(e.statusText=String(g.statusText))}return new Response(a.body?String(a.body):
"",e)};function J(a,b,c){this.B=b;this.o=c;this.ia=a}J.prototype.isSupported=function(){var a=this.B.ampdoc;return a.isSingleDoc()&&a.getRootNode().documentElement.hasAttribute("allow-viewer-render-template")?this.B.hasCapability("viewerRenderTemplate"):!1};J.prototype.fetchAndRenderTemplate=function(a,b,c,d){c=void 0===c?null:c;d=void 0===d?{}:d;var e;c||(e=this.o.maybeFindTemplate(a));return this.B.sendMessageAwaitResponse("viewerRenderTemplate",Qa(this,b,e,c,d))};
function Qa(a,b,c,d,e){e=void 0===e?{}:e;var g=u({type:a.ia}),f="successTemplate",h=d&&d[f]?d[f]:c;h&&(g[f]={type:"amp-mustache",payload:h.innerHTML});var k="errorTemplate",l=d&&d[k]?d[k]:null;l&&(g[k]={type:"amp-mustache",payload:l.innerHTML});e&&Object.assign(g,e);a=b.xhrUrl;c=b.fetchOpt;b=Object.assign({},c);if((d=c.body)&&"function"==typeof d.getFormData){b.headers["Content-Type"]="multipart/form-data;charset=utf-8";c=c.body.entries();d=[];for(e=c.next();!e.done;e=c.next())d.push(e.value);b.body=
d}return u({originalRequest:{input:a,init:b},ampComponent:g})}J.prototype.verifySsrResponse=function(a,b,c){b=Pa(b,c.fetchOpt.responseType);c=c.fetchOpt;(b=b.headers.get("AMP-Access-Control-Allow-Source-Origin"))?(a=F(Ea(a.location.href)).origin,q().assert(b==a,"Returned AMP-Access-Control-Allow-Source-Origin is not equal to the current: "+b+(" vs "+a))):c.requireAmpResponseSourceOrigin&&q().assert(!1,"Response must contain the AMP-Access-Control-Allow-Source-Origin header")};function Ra(a){var b=a.ownerDocument.defaultView;b.FormProxy||(b.FormProxy=Sa(b));var c=b.FormProxy,d=new c(a);"action"in d||Ta(a,d);a.$p=d}
function Sa(a){function b(a){this.h=a}var c=b.prototype,d=a.Object,e=d.prototype,g=[a.HTMLFormElement,a.EventTarget],f=g.reduce(function(a,b){for(b=b&&b.prototype;b&&b!==e&&!(0<=a.indexOf(b));)a.push(b),b=d.getPrototypeOf(b);return a},[]);f.forEach(function(b){var d={},g;for(g in b)if(d.property=a.Object.getOwnPropertyDescriptor(b,g),d.property&&g.toUpperCase()!=g&&!qa(g,"on")&&!e.hasOwnProperty.call(c,g)){if("function"==typeof d.property.value)d.method=d.property.value,c[g]=function(a){return function(){return a.method.apply(this.h,
arguments)}}(d);else{var f={};d.property.get&&(f.get=function(a){return function(){return a.property.get.call(this.h)}}(d));d.property.set&&(f.set=function(a){return function(b){return a.property.set.call(this.h,b)}}(d));a.Object.defineProperty(c,g,f)}d={method:d.method,property:d.property}}});return b}
function Ta(a,b){var c=a.ownerDocument.defaultView.HTMLFormElement.prototype.cloneNode.call(a,!1),d={},e;for(e in c)if(d.name=e,!(d.name in b||d.name.toUpperCase()==d.name||qa(d.name,"on"))){d.desc=Ua[d.name];var g=a[d.name];if(d.desc)if(d.desc.access==K){d.actual=void 0;if(g&&g.nodeType){var f=c=g,h=f.nextSibling,f=f.parentNode;f.removeChild(c);try{d.actual=a[d.name]}finally{f.insertBefore(c,h)}}else d.actual=g;Object.defineProperty(b,d.name,{get:function(a){return function(){return a.actual}}(d)})}else d.desc.access==
L&&(d.attr=d.desc.attr||d.name,Object.defineProperty(b,d.name,{get:function(c){return function(){var d=b.getAttribute(c.attr);return null==d&&void 0!==c.desc.def?c.desc.def:c.desc.type==Va?"true"===d:c.desc.type==M?null!=d:c.desc.type==Wa?(d=d||"",v(a,"url").parse(d).href):d}}(d),set:function(a){return function(c){a.desc.type==M&&(c=c?"":null);null!=c?b.setAttribute(a.attr,c):b.removeAttribute(a.attr)}}(d)}));else Object.defineProperty(b,d.name,{get:function(b){return function(){return a[b.name]}}(d),
set:function(b){return function(c){a[b.name]=c}}(d)});d={actual:d.actual,attr:d.attr,desc:d.desc,name:d.name}}}
var L=1,K=2,Wa=1,Va=2,M=3,Ua={acceptCharset:{access:L,attr:"accept-charset"},accessKey:{access:L,attr:"accesskey"},action:{access:L,type:Wa},attributes:{access:K},autocomplete:{access:L,def:"on"},children:{access:K},dataset:{access:K},dir:{access:L},draggable:{access:L,type:Va,def:!1},elements:{access:K},encoding:{access:K},enctype:{access:L},hidden:{access:L,type:M,def:!1},id:{access:L,def:""},lang:{access:L},localName:{access:K},method:{access:L,def:"get"},name:{access:L},noValidate:{access:L,attr:"novalidate",
type:M,def:!1},prefix:{access:K},spellcheck:{access:L},style:{access:K},target:{access:L,def:""},title:{access:L},translate:{access:L}};function Xa(a,b){return a.hasAttribute("verify-xhr")?new Ya(a,b):new Za(a)}function N(a){this.h=a}N.prototype.onCommit=function(){$a(this);return ab(this)?this.$():Promise.resolve({updatedElements:[],errors:[]})};N.prototype.$=function(){return Promise.resolve({updatedElements:[],errors:[]})};
function ab(a){a=a.h.elements;for(var b=0;b<a.length;b++){var c=a[b];if(!c.disabled)switch(c.type){case "select-multiple":case "select-one":for(var c=c.options,d=0;d<c.length;d++)if(c[d].selected!==c[d].defaultSelected)return!0;break;case "checkbox":case "radio":if(c.checked!==c.defaultChecked)return!0;break;default:if(c.value!==c.defaultValue)return!0}}return!1}function $a(a){(a=a.h.elements)&&C(a,function(a){a.setCustomValidity("")})}function Za(a){N.apply(this,arguments)}n(Za,N);
function Ya(a,b){this.h=a;this.J=b;this.G=null;this.W=[]}n(Ya,N);Ya.prototype.$=function(){var a=this,b=this.J().then(function(){return[]},function(a){return bb(a)});return cb(this,b).then(function(b){return db(a,b)})};function cb(a,b){if(!a.G){a.G=new ka;var c=function(){return a.G=null};a.G.then(c,c)}return a.G.add(b)}
function db(a,b){function c(a){return b.every(function(b){return a.name!==b.name})}var d=[],e=a.W;a.W=b;for(var g=0;g<b.length;g++){var f=b[g],h=q().assertString(f.name,"Verification errors must have a name property"),f=q().assertString(f.message,"Verification errors must have a message property"),h=q().assertElement(a.h.querySelector('[name="'+h+'"]'),"Verification error name property must match a field name");h.checkValidity()&&(h.setCustomValidity(f),d.push(h))}var k=e.filter(c).map(function(b){return a.h.querySelector('[name="'+
b.name+'"]')});return{updatedElements:d.concat(k),errors:b}}function bb(a){return(a=a.response)?a.json().then(function(a){return a.verifyErrors||[]},function(){return[]}):Promise.resolve([])};function O(a,b){this.U=b;this.na=x(a,"viewport");this.aa=y(a.win,"vsync");this.S=null;this.R="";this.M=!1;this.w=a.win.document.createElement("div");Ha(this.w,!1);this.w.classList.add("i-amphtml-validation-bubble");this.w.__BUBBLE_OBJ=this;a.getBody().appendChild(this.w)}O.prototype.isActiveOn=function(a){return this.M&&a==this.S};O.prototype.hide=function(){this.M&&(this.M=!1,this.S=null,this.R="",this.aa.run({measure:void 0,mutate:eb},{bubbleElement:this.w}))};
O.prototype.show=function(a,b){if(!this.isActiveOn(a)||b!=this.R){this.M=!0;this.S=a;this.R=b;var c={message:b,targetElement:a,bubbleElement:this.w,viewport:this.na,id:this.U};this.aa.run({measure:fb,mutate:gb},c)}};function eb(a){a.bubbleElement.removeAttribute("aria-alert");a.bubbleElement.removeAttribute("role");for(var b=a.bubbleElement;b.firstChild;)b.removeChild(b.firstChild);Ha(a.bubbleElement,!1)}function fb(a){a.targetRect=a.viewport.getLayoutRect(a.targetElement)}
function gb(a){for(var b=a.bubbleElement;b.firstChild;)b.removeChild(b.firstChild);var c=a.bubbleElement.ownerDocument.createElement("div");c.id="bubble-message-"+a.id;c.textContent=a.message;a.bubbleElement.setAttribute("aria-labeledby",c.id);a.bubbleElement.setAttribute("role","alert");a.bubbleElement.setAttribute("aria-live","assertive");a.bubbleElement.appendChild(c);Ha(a.bubbleElement,!0);b=a.bubbleElement;a={top:a.targetRect.top-10+"px",left:a.targetRect.left+a.targetRect.width/2+"px"};for(var d in a){var e=
b,g=a[d],f;f=e.style;var h=d;if(qa(h,"--"))f=h;else{G||(G=r());var k=G[h];if(!k){k=h;if(void 0===f[h]){var l=h.charAt(0).toUpperCase()+h.slice(1);b:{for(var t=0;t<Ga.length;t++){var Ca=Ga[t]+l;if(void 0!==f[Ca]){l=Ca;break b}}l=""}void 0!==f[l]&&(k=l)}G[h]=k}f=k}f&&(e.style[f]=g)}};var hb,ib,jb=0;function P(a){this.form=a;this.ampdoc=z(a);this.resources=x(a,"resources");this.root=this.ampdoc.getRootNode();this.L=null}m=P.prototype;m.report=function(){};m.onBlur=function(){};m.onInput=function(){};m.inputs=function(){return this.form.querySelectorAll("input,select,textarea")};m.fireValidityEventIfNecessary=function(){var a=this.L;this.L=this.form.checkValidity();if(a!==this.L){var b=Fa(this.form.ownerDocument.defaultView,this.L?"valid":"invalid",null,{bubbles:!0});this.form.dispatchEvent(b)}};
function kb(a){P.apply(this,arguments)}n(kb,P);kb.prototype.report=function(){this.form.reportValidity();this.fireValidityEventIfNecessary()};function Q(a){P.call(this,a);var b="i-amphtml-validation-bubble-"+jb++;this.D=new O(this.ampdoc,b)}n(Q,P);Q.prototype.report=function(){for(var a=this.inputs(),b=0;b<a.length;b++)if(!a[b].checkValidity()){a[b].focus();this.D.show(a[b],a[b].validationMessage);break}this.fireValidityEventIfNecessary()};Q.prototype.onBlur=function(){this.D.hide()};
Q.prototype.onInput=function(a){a=a.target;this.D.isActiveOn(a)&&(a.checkValidity()?(a.removeAttribute("aria-invalid"),this.D.hide()):(a.setAttribute("aria-invalid","true"),this.D.show(a,a.validationMessage)))};function R(a){P.call(this,a)}n(R,P);m=R.prototype;m.reportInput=function(a){var b=lb(a);b&&this.showValidationFor(a,b)};m.hideAllValidations=function(){for(var a=this.inputs(),b=0;b<a.length;b++)this.hideValidationFor(a[b])};
m.getValidationFor=function(a,b){if(!a.id)return null;var c="__AMP_VALIDATION_"+b;c in a||(a[c]=this.root.querySelector("[visible-when-invalid="+b+"]"+("[validation-for="+a.id+"]")));return a[c]};m.showValidationFor=function(a,b){var c=this.getValidationFor(a,b);c&&(c.textContent.trim()||(c.textContent=a.validationMessage),a.__AMP_VISIBLE_VALIDATION=c,this.resources.mutateElement(a,function(){return a.setAttribute("aria-invalid","true")}),this.resources.mutateElement(c,function(){return c.classList.add("visible")}))};
m.hideValidationFor=function(a){var b=this.getVisibleValidationFor(a);b&&(delete a.__AMP_VISIBLE_VALIDATION,this.resources.mutateElement(a,function(){return a.removeAttribute("aria-invalid")}),this.resources.mutateElement(b,function(){return b.classList.remove("visible")}))};m.getVisibleValidationFor=function(a){return a.__AMP_VISIBLE_VALIDATION};m.shouldValidateOnInteraction=function(){throw Error("Not Implemented");};
m.onInteraction=function(a){a=a.target;var b=!!a.checkValidity&&this.shouldValidateOnInteraction(a);this.hideValidationFor(a);b&&!a.checkValidity()&&this.reportInput(a)};m.onBlur=function(a){this.onInteraction(a)};m.onInput=function(a){this.onInteraction(a)};function S(a){R.apply(this,arguments)}n(S,R);S.prototype.report=function(){this.hideAllValidations();for(var a=this.inputs(),b=0;b<a.length;b++)if(!a[b].checkValidity()){this.reportInput(a[b]);a[b].focus();break}this.fireValidityEventIfNecessary()};
S.prototype.shouldValidateOnInteraction=function(a){return!!this.getVisibleValidationFor(a)};function T(a){R.apply(this,arguments)}n(T,R);T.prototype.report=function(){this.hideAllValidations();for(var a=null,b=this.inputs(),c=0;c<b.length;c++)b[c].checkValidity()||(a=a||b[c],this.reportInput(b[c]));a&&a.focus();this.fireValidityEventIfNecessary()};T.prototype.shouldValidateOnInteraction=function(a){return!!this.getVisibleValidationFor(a)};function U(a){R.apply(this,arguments)}n(U,R);
U.prototype.shouldValidateOnInteraction=function(){return!0};U.prototype.onInteraction=function(a){R.prototype.onInteraction.call(this,a);this.fireValidityEventIfNecessary()};function V(a){T.apply(this,arguments)}n(V,T);V.prototype.shouldValidateOnInteraction=function(){return!0};V.prototype.onInteraction=function(a){T.prototype.onInteraction.call(this,a);this.fireValidityEventIfNecessary()};
function mb(a){var b=a.getAttribute("custom-validation-reporting");switch(b){case "as-you-go":return new U(a);case "show-all-on-submit":return new T(a);case "interact-and-submit":return new V(a);case "show-first-on-submit":return new S(a)}a.ownerDocument&&void 0===hb&&(hb=!!document.createElement("form").reportValidity);return hb?new kb(a):new Q(a)}
function lb(a){var b=["badInput"],c;for(c in a.validity)b.includes(c)||b.push(c);c=b.filter(function(b){return!0===a.validity[b]});return c.length?c[0]:null};var nb=["amp-selector"];
function ob(a,b){var c=this;try{Ra(a)}catch(g){fa().error("amp-form","form proxy failed to install",g)}a.__AMP_FORM=this;this.U=b;this.j=a.ownerDocument.defaultView;this.la=y(this.j,"timer");this.Z=v(a,"url-replace");this.T=null;this.h=a;this.o=y(this.j,"templates");this.ra=y(this.j,"xhr");this.H=v(this.h,"action");this.ha=x(this.h,"resources");this.B=x(this.h,"viewer");this.C=new J("amp-form",this.B,this.o);this.l=(this.h.getAttribute("method")||"GET").toUpperCase();this.ka=this.h.getAttribute("target");
this.F=pb(this,"action-xhr");this.qa=pb(this,"verify-xhr");this.Y=!this.h.hasAttribute("novalidate");this.h.setAttribute("novalidate","");this.Y||this.h.setAttribute("amp-novalidate","");this.h.classList.add("i-amphtml-form");var d=this.h.querySelectorAll('[type="submit"]');this.ja=da(d);this.m="initial";a=this.h.elements;for(b=0;b<a.length;b++){var e=a[b].name;q().assert("__amp_source_origin"!=e&&"__amp_form_verify"!=e,"Illegal input name, %s found: %s",e,a[b])}this.N=mb(this.h);this.ma=Xa(this.h,
function(){return qb(c)});this.H.installActionHandler(this.h,this.ba.bind(this),100);rb(this);this.fa=this.pa=null}function pb(a,b){var c=a.h.getAttribute(b);if(c){var d=v(a.h,"url");d.assertHttpsUrl(c,a.h,b);q().assert(!d.isProxyOrigin(c),"form "+b+" should not be on AMP CDN: %s",a.h)}return c}m=ob.prototype;
m.requestForFormFetch=function(a,b,c){var d,e,g="GET"==b||"HEAD"==b;if(g){sb(this);var f=H(this.h);c&&ha(f,c);var h=[],k;for(k in f){var l=f[k];if(null!=l)if(Array.isArray(l))for(var t=0;t<l.length;t++)h.push(encodeURIComponent(k)+"="+encodeURIComponent(l[t]));else h.push(encodeURIComponent(k)+"="+encodeURIComponent(l))}d=Da(a,h.join("&"))}else for(f in d=a,e=new I(this.h),c)e.append(f,c[f]);return{xhrUrl:d,fetchOpt:u({body:e,method:b,credentials:"include",headers:u({Accept:"application/json"})})}};
m.ba=function(a){var b=this;"submit"==a.method?tb(this).then(function(){var c=a;"submitting"!=b.m&&ub(b)&&(vb(b,c.trust),"GET"!=b.l||b.F||b.h.submit())}):"clear"===a.method&&wb(this);return null};function tb(a){if(a.T)return a.T;var b=a.h.querySelectorAll(nb.join(",")),c=da(b).map(function(a){return a.whenBuilt()});return a.T=xb(a,c,2E3)}
function rb(a){a.B.whenNextVisible().then(function(){var b=a.h.querySelector("[autofocus]");if(b)try{b.focus()}catch(c){}});a.h.addEventListener("submit",a.da.bind(a),!0);a.h.addEventListener("blur",function(b){yb(b.target);a.N.onBlur(b)},!0);a.C.isSupported()||a.h.addEventListener("change",function(b){a.ma.onCommit().then(function(c){var d=c.updatedElements,e=c.errors;d.forEach(yb);a.N.onBlur(b);"verifying"===a.m&&(e.length?(W(a,"verify-error"),X(a,{verifyErrors:e}).then(function(){Y(a,"verify-error",
e)})):W(a,"initial"))})});a.h.addEventListener("input",function(b){yb(b.target);a.N.onInput(b)})}function zb(a,b){Ab(a,"Form analytics not supported");var c={},d=H(a.h),e;for(e in d)Object.prototype.hasOwnProperty.call(d,e)&&(c["formFields["+e+"]"]=d[e].join(","));c.formId=a.h.id;Na(a.h,b,c)}
function wb(a){a.h.reset();W(a,"initial");a.h.classList.remove("user-valid");a.h.classList.remove("user-invalid");var b=a.h.querySelectorAll(".user-valid, .user-invalid");C(b,function(a){a.classList.remove("user-valid");a.classList.remove("user-invalid")});var c=a.h.querySelectorAll(".visible[validation-for]");C(c,function(a){a.classList.remove("visible")});Bb(a.h)}
m.da=function(a){"submitting"!=this.m&&ub(this)?((this.F||"POST"==this.l)&&a.preventDefault(),vb(this,100)):(a.stopImmediatePropagation(),a.preventDefault())};function vb(a,b){var c=Cb(a);if(a.F)Db(a,c,b);else if("POST"==a.l)q().assert(!1,"Only XHR based (via action-xhr attribute) submissions are supported for POST requests. %s",a.h);else if("GET"==a.l){var d=c;Ab(a,"Non-XHR GETs not supported.");sb(a);for(var e=0;e<d.length;e++)a.Z.expandInputValueSync(d[e]);zb(a,"amp-form-submit")}}
function Cb(a){return a.h.querySelectorAll('[type="hidden"][data-amp-replace]')}function qb(a){if("submitting"===a.m)return Promise.resolve();W(a,"verifying");Y(a,"verify",null);return Eb(a,Cb(a)).then(function(){var b={};return a.J(a.qa,a.l,(b.__amp_form_verify=!0,b))})}function Db(a,b,c){W(a,"submitting");var d=Eb(a,b);a.C.isSupported()?d.then(function(){return Fb(a,c)}):d.then(function(){Gb(a,c);return a.J(a.F,a.l)}).then(function(b){return Hb(a,b)},function(b){return Ib(a,b)})}
function Fb(a,b){var c,d=H(a.h);return X(a,d).then(function(){a.H.trigger(a.h,"submit",null,b)}).then(function(){var b=c=a.requestForFormFetch(a.F,a.l),d=c.fetchOpt||{},f;f=d.method;void 0===f?f="GET":(f=f.toUpperCase(),Oa.includes(f));d.method=f;d.headers=d.headers||u({});b.fetchOpt=d;var b=c,h=a.j;f=c.xhrUrl;d=c.fetchOpt;!1===d.ampCors&&(d.requireAmpResponseSourceOrigin=!1);!0===d.requireAmpResponseSourceOrigin&&fa().error("XHR","requireAmpResponseSourceOrigin is deprecated, use ampCors instead");
void 0===d.requireAmpResponseSourceOrigin&&(d.requireAmpResponseSourceOrigin=!0);h=h.origin||F(h.location.href).origin;f=F(f).origin;h==f&&(d.headers=d.headers||{},d.headers["AMP-Same-Origin"]="true");b.fetchOpt=d;b=c;f=c.xhrUrl;if(!1!==c.fetchOpt.ampCors){d=a.j;var h=F(f).search,k=Object.create(null);if(h)for(var l;l=ba.exec(h);){var t=aa(l[1],l[1]);l=l[2]?aa(l[2],l[2]):"";k[t]=l}q().assert(!("__amp_source_origin"in k),"Source origin is not allowed in %s",f);d=F(Ea(d.location.href)).origin;f=Da(f,
encodeURIComponent("__amp_source_origin")+"="+encodeURIComponent(d),void 0)}b.xhrUrl=f;return a.C.fetchAndRenderTemplate(a.h,c,Jb(a))}).then(function(b){return Kb(a,b,c)},function(b){return Lb(a,b)})}function Jb(a){var b=a.h.querySelector("div[submit-success]"),c=a.h.querySelector("div[submit-error]"),d,e;b&&(d=a.o.maybeFindTemplate(b));c&&(e=a.o.maybeFindTemplate(c));return{successTemplate:d,errorTemplate:e}}
function Lb(a,b){W(a,"submit-error");q().error("amp-form","Form submission failed: "+b);return ja(function(){X(a,b||{}).then(function(){Y(a,"submit-error",b)})})}function Gb(a,b){zb(a,"amp-form-submit");var c=H(a.h);X(a,c).then(function(){a.H.trigger(a.h,"submit",null,b)})}function Eb(a,b){for(var c=[],d=0;d<b.length;d++)c.push(a.Z.expandInputValueAsync(b[d]));return xb(a,c,100)}
m.J=function(a,b,c){Ab(this,"XHRs should be proxied.");a=this.requestForFormFetch(a,b,c);return this.ra.fetch(a.xhrUrl,a.fetchOpt)};function Kb(a,b,c){a.C.verifySsrResponse(a.j,b,c);return Mb(a,ja(function(){return b.html}))}function Hb(a,b){return Mb(a,b.json()).then(function(){zb(a,"amp-form-submit-success");Nb(a,b)})}
function Mb(a,b){return b.then(function(b){W(a,"submit-success");X(a,b||{}).then(function(){Y(a,"submit-success",b)})},function(a){q().error("amp-form","Failed to parse response JSON: "+a)})}function Ib(a,b){return(b&&b.response?b.response.json().catch(function(){return null}):Promise.resolve(null)).then(function(c){zb(a,"amp-form-submit-error");W(a,"submit-error");X(a,c||{}).then(function(){Y(a,"submit-error",c)});Nb(a,b.response);q().error("amp-form","Form submission failed: "+b)})}
function Ab(a,b){var c=a.C.isSupported();q().assert(!1===c,"[amp-form]: viewerRenderTemplate | "+b)}function sb(a){var b=a.h.querySelectorAll("input[type=password],input[type=file]");q().assert(0==b.length,"input[type=password] or input[type=file] may only appear in form[method=post]")}function ub(a){void 0===ib&&(ib=!!a.j.document.createElement("input").checkValidity);if(ib){var b=Ob(a.h);if(a.Y)return a.N.report(),b}return!0}
function Nb(a,b){Ab(a,"Redirects not supported.");if(b&&b.headers){var c=b.headers.get("AMP-Redirect-To");if(c){q().assert("_blank"!=a.ka,"Redirecting to target=_blank using AMP-Redirect-To is currently not supported, use target=_top instead. %s",a.h);try{var d=v(a.h,"url");d.assertAbsoluteHttpOrHttpsUrl(c);d.assertHttpsUrl(c,"AMP-Redirect-To","Url")}catch(e){q().assert(!1,"The `AMP-Redirect-To` header value must be an absolute URL starting with https://. Found %s",c)}b=z(a.h);b=A(b);w(b,"navigation").navigateTo(a.j,
c,"AMP-Redirect-To")}}}function Y(a,b,c){c=Fa(a.j,"amp-form."+b,u({response:c}));a.H.trigger(a.h,b,c,100)}function xb(a,b,c){return Promise.race([Promise.all(b),a.la.promise(c)])}function W(a,b){var c=a.m;a.h.classList.remove("amp-form-"+c);a.h.classList.add("amp-form-"+b);Pb(a,c);a.m=b;a.ja.forEach(function(a){"submitting"==b?a.setAttribute("disabled",""):a.removeAttribute("disabled")})}
function X(a,b){var c=a.h.querySelector("["+a.m+"]"),d=Promise.resolve();if(c){var e="rendered-message-"+a.U;c.setAttribute("role","alert");c.setAttribute("aria-labeledby",e);c.setAttribute("aria-live","assertive");a.o.hasTemplate(c)?d=a.o.findAndRenderTemplate(c,b).then(function(b){b.id=e;b.setAttribute("i-amphtml-rendered","");c.appendChild(b);var d=Fa(a.j,"amp:dom-update",null,{bubbles:!0});c.dispatchEvent(d)}):a.ha.mutateElement(c,function(){})}return d}
function Pb(a,b){if(a=a.h.querySelector("["+b+"]")){var c;if(null==B){b=a.ownerDocument;try{c=b.createElement("div");var d=b.createElement("div");c.appendChild(d);B=c.querySelector(":scope div")===d}catch(g){B=!1}}B?c=a.querySelector(":scope > [i-amphtml-rendered]"):(a.classList.add("i-amphtml-scoped"),c=a.querySelector(".i-amphtml-scoped > [i-amphtml-rendered]"),a.classList.remove("i-amphtml-scoped"));var e=c;e&&(c=e,c.parentElement&&c.parentElement.removeChild(c))}}m.sa=function(){return this.fa};
m.ta=function(){return this.pa};function Ob(a){C(a.querySelectorAll("input,select,textarea,fieldset"),function(a){return Z(a)});return Z(a)}function Bb(a){var b=document.createElement("input"),c={},d;for(d in b.validity){c.validityState=d;var e=a.querySelectorAll("."+String(c.validityState).replace(oa,pa));C(e,function(a){return function(b){return b.classList.remove(a.validityState)}}(c));c={validityState:c.validityState}}}
function Z(a,b){b=void 0===b?!1:b;if(!a.checkValidity)return!0;var c=!1,d=a.classList.contains("user-valid")?"valid":a.classList.contains("user-invalid")?"invalid":"none",e=a.checkValidity();"valid"!=d&&e?(a.classList.add("user-valid"),a.classList.remove("user-invalid"),c="invalid"==d):"invalid"==d||e||(a.classList.add("user-invalid"),a.classList.remove("user-valid"),c=!0);if(a.validity)for(var g in a.validity)a.classList.toggle(g,a.validity[g]);if(b&&c){g=sa(a);for(var f=0;f<g.length;f++)Z(g[f]);
a.form&&Z(a.form)}return e}function yb(a){Z(a,!0)}function Qb(a){this.oa=Rb(a).then(function(){return Sb(a)})}Qb.prototype.whenInitialized=function(){return this.oa};function Rb(a){var b=new ia;Ia(a,b.resolve);return b.promise}function Sb(a){return a.whenReady().then(function(){Tb(a.getRootNode().querySelectorAll("form"));Ub(a.getRootNode())})}function Tb(a){a&&C(a,function(a,c){var b=a.__AMP_FORM||null;b||new ob(a,"amp-form-"+c)})}
function Ub(a){a.addEventListener("amp:dom-update",function(){Tb(a.querySelectorAll("form"))})}(function(a){a.registerServiceForDoc("amp-form",Qb)})(self.AMP);
})});
//# sourceMappingURL=amp-form-0.1.js.map

